package com.psp.enviocorreo;

import jakarta.mail.MessagingException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Alejandro
 */
public class InterfazCorreo extends javax.swing.JFrame {

    /**
     * Creates new form InterfazCorreo
     */
    public InterfazCorreo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBox_Destinatario = new javax.swing.JTextField();
        txtBox_Asunto = new javax.swing.JTextField();
        scrollPane = new javax.swing.JScrollPane();
        txtArea_Texto = new javax.swing.JTextArea();
        btn_seleccionArchivo = new javax.swing.JButton();
        btn_envioCorreo = new javax.swing.JButton();
        txtBox_Ruta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtArea_Texto.setColumns(20);
        txtArea_Texto.setRows(5);
        scrollPane.setViewportView(txtArea_Texto);
        txtArea_Texto.getAccessibleContext().setAccessibleParent(this);

        btn_seleccionArchivo.setText("Archivo");
        btn_seleccionArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_seleccionArchivoMouseClicked(evt);
            }
        });

        btn_envioCorreo.setText("Enviar");
        btn_envioCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_envioCorreoMouseClicked(evt);
            }
        });

        txtBox_Ruta.setEditable(false);

        jLabel1.setText("Destinatario");

        jLabel2.setText("Asunto");

        jLabel3.setText("Cuerpo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(txtBox_Ruta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_seleccionArchivo)
                .addGap(155, 155, 155)
                .addComponent(btn_envioCorreo)
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(txtBox_Destinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBox_Asunto))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBox_Destinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBox_Asunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBox_Ruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_seleccionArchivo)
                    .addComponent(btn_envioCorreo))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_seleccionArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_seleccionArchivoMouseClicked
        JFileChooser jfseleccionador = new JFileChooser();
        jfseleccionador.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int val = jfseleccionador.showOpenDialog(null);

        if (val == JFileChooser.OPEN_DIALOG) {
            String pathAbsoluto = jfseleccionador.getSelectedFile().getAbsolutePath();            
            txtBox_Ruta.setText(pathAbsoluto);
        }
    }//GEN-LAST:event_btn_seleccionArchivoMouseClicked

    private void btn_envioCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_envioCorreoMouseClicked
        EnvioCorreo envioCorreo = new EnvioCorreo();
        
        try {
            
            if(!"".equals(txtBox_Destinatario.getText()) && !"".equals(txtBox_Asunto.getText()) && !"".equals(txtArea_Texto.getText()) && !"".equals(txtBox_Ruta.getText())) {
                envioCorreo.enviarMensajeConAdjunto("ale.fernandez@gmx.es", txtBox_Destinatario.getText(), txtBox_Asunto.getText(),
                    txtArea_Texto.getText(), "ale.fernandez@gmx.es", "PSPIESBelen", txtBox_Ruta.getText());
                
                txtBox_Destinatario.setText("");
                txtBox_Asunto.setText("");
                txtArea_Texto.setText("");
                txtBox_Ruta.setText("");
            } else {                
                JOptionPane.showMessageDialog(rootPane, "Campos no rellenados.");
            }
            
        } catch (MessagingException ex) {
            Logger.getLogger(InterfazCorreo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(InterfazCorreo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_envioCorreoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazCorreo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_envioCorreo;
    private javax.swing.JButton btn_seleccionArchivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTextArea txtArea_Texto;
    private javax.swing.JTextField txtBox_Asunto;
    private javax.swing.JTextField txtBox_Destinatario;
    private javax.swing.JTextField txtBox_Ruta;
    // End of variables declaration//GEN-END:variables
}
